<?php

namespace AppBundle\Repository;

/**
 * JourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourRepository extends \Doctrine\ORM\EntityRepository {

    public function prochainsJours() {
        $query = $this->createQueryBuilder('j');

        $query->where('j.day >= :date ');
        $query->setParameter('date', new \DateTime());

        $result = $query->getQuery()->getResult();

        return $result;
    }

}
