<?php

namespace AppBundle\Repository;

/**
 * ValeurCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValeurCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
