# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   
    weezjump.resa.services:
        class: AppBundle\Services\WeezjumpResaServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]
   
    creation.jour.services:
        class: AppBundle\Services\CreationJourServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]
   
    creation.creneau.services:
        class: AppBundle\Services\CreationCreneauServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]