# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   
    weezjump.resa.services:
        class: AppBundle\Services\WeezjumpResaServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]
   
    jour.services:
        class: AppBundle\Services\JourServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]
   
    creneau.services:
        class: AppBundle\Services\CreneauServices
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@security.token_storage" ]