creneau_index:
    path:     /jour/{id}
    defaults: { _controller: "AppBundle:Creneau:index" }
    methods:  GET

creneau_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:Creneau:show" }
    methods:  GET

creneau_new:
    path:     /new
    defaults: { _controller: "AppBundle:Creneau:new" }
    methods:  [GET, POST]

creneau_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:Creneau:edit" }
    methods:  [GET, POST]

creneau_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:Creneau:delete" }
    methods:  DELETE
