valeurcategorie_index:
    path:     /
    defaults: { _controller: "AppBundle:ValeurCategorie:index" }
    methods:  GET

valeurcategorie_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ValeurCategorie:show" }
    methods:  GET

valeurcategorie_new:
    path:     /new/{id_creneau}/{id_categorie}
    defaults: { _controller: "AppBundle:ValeurCategorie:new" }
    methods:  [GET]

valeurcategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ValeurCategorie:edit" }
    methods:  [GET, POST]

valeurcategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ValeurCategorie:delete" }
    methods:  DELETE
