app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_jour:
    resource: "@AppBundle/Resources/config/routing/jour.yml"
    prefix:   /jour

app_creneau:
    resource: "@AppBundle/Resources/config/routing/creneau.yml"
    prefix:   /creneau

app_configuration:
    resource: "@AppBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration

app_categorie:
    resource: "@AppBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

app_valeurcategorie:
    resource: "@AppBundle/Resources/config/routing/valeurcategorie.yml"
    prefix:   /valeurcategorie
    
parametres:
    path:     /parametres
    defaults: { _controller: "AppBundle:Default:parametres"}
    methods:  GET    
    
statistiques:
    path:     /statistiques/{date}
    defaults: { _controller: "AppBundle:Default:statistiques" , date: null}
    methods:  GET    
    
homepage:
    path:     /date/{date}
    defaults: { _controller: "AppBundle:Default:index" , date: null}
    methods:  GET    

